export default {
  // imgUrl: require('../../../assets/image/newsdetail.png'),
  imgUrl: '',
  title: 'Phẫu thuật thành công cho bệnh nhân nhờ nguồn máu kịp thời',
  time: '5 phút trước',
  body: `Semper nibh eget aliquet sed in consequat, morbi vel. Sed tristique aliquam sagittis duis id vel. Nunc egestas elementum lorem placerat donec. Id aliquam non fringilla amet purus ut. Ipsum et convallis ultrices commodo elit enim, ac pellentesque a. Sit tincidunt in ut nisl quisque cursus tellus phasellus. Pulvinar enim congue pulvinar sed. Sed eros ante ipsum nulla auctor a felis. Ac id et magna sed cursus nunc proin ullamcorper. Congue at id venenatis vel commodo. Molestie ac elit cursus cras cursus magna donec habitant dignissim. Elit, nibh proin mi fringilla tincidunt. Eu ante nec pulvinar tellus aliquam eu. Habitant et ut turpis morbi massa. Sed tellus quam velit arcu urna, tincidunt sodales iaculis mauris.
  Quam nisi, et, commodo arcu arcu. Nascetur pellentesque scelerisque netus est vitae. Nisl suscipit volutpat velit platea id posuere vel lacus. Non sem fames eget orci, turpis. Et nisl lacus, volutpat lacinia lorem elementum auctor nibh ultrices. Leo vitae placerat ante volutpat. Quam diam sed eget lectus velit. Turpis consectetur ut faucibus elit. Lacus, leo id lobortis viverra nibh viverra.
  Vehicula egestas sed libero ante eget. Ornare eget mattis eget id mi aliquam posuere lorem fames. Faucibus auctor placerat tellus at. Id massa, at ullamcorper vestibulum malesuada velit purus elit ut. Amet, nunc etiam nisl, donec nisl convallis tincidunt at sem. Varius commodo ullamcorper et eu risus, nisl ullamcorper. Nec velit, suspendisse quam nunc. Duis sit id elementum, proin. Enim commodo vulputate rhoncus donec non amet vel, quisque. Sodales pellentesque amet tortor pulvinar leo, vestibulum at morbi ultricies. Sodales tincidunt justo, sit luctus tincidunt. Tortor risus lacus ipsum sed ut. Consequat eget sit adipiscing diam, nunc sed integer purus. Netus dignissim nisl turpis nunc pulvinar felis id sed senectus. Ultrices lacus purus vel eget dui est accumsan sed.`,
};
